DROP DATABASE IF EXISTS STORE;
CREATE DATABASE STORE;
USE STORE;
CREATE TABLE PRODUCTS (
    ID_PRODUCT INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(256) NULL,
    PRICE DECIMAL(4,2) NOT NULL,
    PRIMARY KEY (ID_PRODUCT)
    ) ENGINE = InnoDB;

CREATE TABLE TIENDA (
    ID_TIENDA INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50),
    ADDRESS VARCHAR(100),
    PRIMARY KEY (ID_TIENDA)
    ) ENGINE = InnoDB;
    
INSERT INTO PRODUCTS (ID_PRODUCT, NAME, DESCRIPTION, PRICE)
VALUES (001, 'PERA', 'Fruta pera', 2);
INSERT INTO PRODUCTS (ID_PRODUCT, NAME, DESCRIPTION, PRICE)
VALUES (002, 'POLLO', 'Producto carnico', 4.5);
INSERT INTO PRODUCTS (ID_PRODUCT, NAME, DESCRIPTION, PRICE)
VALUES (003, 'PLATANO', 'Fruta platano', 1.8);
INSERT INTO PRODUCTS (ID_PRODUCT, NAME, DESCRIPTION, PRICE)
VALUES (004, 'SALMON', 'Pescado salmon', 5.4);
INSERT INTO PRODUCTS (ID_PRODUCT, NAME, DESCRIPTION, PRICE)
VALUES (005, 'NARANJA', 'Fruta naranja', 1.5);
INSERT INTO PRODUCTS (ID_PRODUCT, NAME, DESCRIPTION, PRICE)
VALUES (006, 'LIMON', 'Fruta limon', 1.9);
INSERT INTO PRODUCTS (ID_PRODUCT, NAME, DESCRIPTION, PRICE)
VALUES (007, 'PIÑA', 'Fruta piña', 4.2);
INSERT INTO PRODUCTS (ID_PRODUCT, NAME, DESCRIPTION, PRICE)
VALUES (008, 'LANGOSTA', 'Marisco', 14);
INSERT INTO PRODUCTS (ID_PRODUCT, NAME, DESCRIPTION, PRICE)
VALUES (009, 'PISTACHOS', 'Frutos secos', 1.8);

VALUES INTO TIENDA (ID_TIENDA, NAME, ADDRESS)
VALUES (1, "MERCADONA", "Calle girasol 20");
VALUES INTO TIENDA (ID_TIENDA, NAME, ADDRESS)
VALUES (2, "LIDL", "Calle Mazapán 24");
VALUES INTO TIENDA (ID_TIENDA, NAME, ADDRESS)
VALUES (3, "CARREFOUR", "Avenida Primera");
VALUES INTO TIENDA (ID_TIENDA, NAME, ADDRESS)
VALUES (4, "EROSKI", "Calle Eusebio Estada");
VALUES INTO TIENDA (ID_TIENDA, NAME, ADDRESS)
VALUES (5, "ALDI", "Calle Bartolomé");